codecov:
  max_report_age: off

coverage:
  status:
    project:
      default:
        #basic
        target: auto
        threshold: 1%
        base: auto 
        branches: 
          - master
        if_ci_failed: error #success, failure, error, ignore
        informational: true
        only_pulls: false

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
